CREATE TABLE t09 (`name` CHAR(255))

CREATE TABLE 	t10 (`NAME` VARCHAR(21844))
DROP TABLE t11

# 里面填写的是字符, 不是字节
CREATE TABLE t11 (`name` VARCHAR(32766)) CHARACTER SET gbk

CREATE TABLE t12 (`name` CHAR(4));

INSERT INTO t12 VALUES ('韩顺平6')

SELECT * FROM t12
DROP TABLE t13
CREATE TABLE t13(`name` VARCHAR(10));

INSERT INTO t13 VALUES ('改写归正, 回头是岸')

SELECT * FROM t13

CREATE TABLE t14 (article TEXT, num MEDIUMTEXT , `name` LONGTEXT)
INSERT INTO t14 values('韩顺平nb', '韩顺平6', '韩顺平1212')
SELECT * FROM t14



